== Implementation-defined Constant Parameters

Each hart supporting a matrix extension defines four parameters:

. The maximum size in bits of a matrix element that any operation can produce or consume, stem:[\rm{ELEN} \ge 8], which must be a power of 2.
. The number of bits in a single matrix tile register, MLEN, which must be a power of 2, and must be no greater than 2^32^.
. The number of bits in a row of a single matrix tile register, RLEN, which must be a power of 2, and must be no greater than 2^16^.
. The multiple of length for matrix accumulation registers, AMUL, where the number of bits in a row of a single matrix accumulation register is stem:[\rm{RLEN} \times \rm{AMUL}], and the number of bits in a single matrix accumulation register is stem:[\rm{MLEN} \times \rm{AMUL}].

Some constraints on these parameters are defined as following.

. stem:[\rm{ELEN} \le \rm{RLEN} \le \rm{MLEN}], this supports matrix tile size from stem:[1 \times 1] to stem:[2^{16} \times 2^{16}].
. For implmentations without widening accumulation space, stem:[\rm{AMUL} = 1].
. For implmentations with double-widening accumulation space, stem:[\rm{AMUL} = 2].
. For implmentations with quadruple-widening accumulation space, stem:[\rm{AMUL} = 4].
. For implmentations with octuple-widening accumulation space, stem:[\rm{AMUL} = 8].
. AMUL with any other value is not allowed.
